version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: brainloggers-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brainloggers_db
    ports:
      - "3331:5432"
    volumes:
      - brainloggers_postgres_data:/var/lib/postgresql/data
    networks:
      - brainloggers-network

  redis:
    image: redis:7-alpine
    container_name: brainloggers-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "3332:6379"
    volumes:
      - brainloggers_redis_data:/data
    networks:
      - brainloggers-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: brainloggers-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - brainloggers_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - brainloggers-network

# Networks definition
networks:
  brainloggers-network:
    driver: bridge

volumes:
  brainloggers_postgres_data:
  brainloggers_redis_data:
  brainloggers_rabbitmq_data:
